on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  docker-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Split Name
        id: split
        env:
          PATH_CANDIDATE: ${{ inputs.project }}
        run: echo "::set-output name=imagename::${PATH_CANDIDATE##*/}"
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker
        uses: docker/build-push-action@v4
        with:
          context: ./src/${{ inputs.project }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.split.outputs.imagename }}:${{ github.sha }}
      - name: Scan for Vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.split.outputs.imagename }}:${{ github.sha }}'
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'