on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  docker-main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Split Name
        id: split
        env:
          PATH_CANDIDATE: ${{ inputs.project }}
        run: echo "::set-output name=imagename::${PATH_CANDIDATE##*/}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker
        uses: docker/build-push-action@v4
        with:
          context: ./src/${{ inputs.project }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{env.REGISTRY}}/${{ steps.split.outputs.imagename }}:${{ github.sha }}