on:
  push:
    branches:
      - feature/add-infrastructure-scripts

jobs:
  terraform-worflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      - name: Prepare Workspace
        run: |
          cp -a infrastructure/. src/shared-infra
      - name: Dev Plan
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        run: |
          cd src/shared-infra
          terraform init
          terraform workspace select -or-create dev
          terraform validate
          terraform plan
