name: "PR Ad Service"

on:
  pull_request:
    paths:
      - 'src/adservice/**'
      - '.github/shared/**'
      - '.github/adservice-pr.yml'
      - '.github/adservice-main.yml'
    branches:
      - main

jobs:
  docker-workflow:
    uses: ./.github/workflows/shared/docker-pr.yml
    with:
      project: adservice