name: "Main Cart Service"

on:
  push:
    paths:
      - 'src/cartservice/**'
    branches:
      - main
jobs:
  docker-workflow:
    uses: ./.github/workflows/_docker-main.yml
    with:
      project: cartservice/src