name: "Cart Service Infra Main"

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/cartservice/app.auto.tfvars*'
    branches:
      - main

jobs:
  dev-workflow:
    uses: ./.github/workflows/_infra-main.yml
    secrets: inherit
    with:
      project: cartservice
      env: dev
  stage-workflow:
    needs: [dev-workflow]
    uses: ./.github/workflows/_infra-main.yml
    secrets: inherit
    with:
      project: cartservice
      env: stage
  prod-workflow:
    needs: [stage-workflow]
    uses: ./.github/workflows/_infra-main.yml
    secrets: inherit
    with:
      project: cartservice
      env: prod