name: "PR Cart Service"

on:
  pull_request:
    paths:
      - 'src/cartservice/**'
    branches:
      - main

jobs:
  docker-workflow:
    uses: ./.github/workflows/_docker-pr.yml
    with:
      project: cartservice/src
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dotnet
        uses: actions/setup-dotnet@v4
        env:
          DOTNET_INSTALL_DIR: "./.dotnet"
        with:
          dotnet-version: '8.0'
      - name: Run Tests
        run: |
          dotnet test src/cartservice/