name: "PR Checkout Service"

on:
  pull_request:
    paths:
      - 'src/checkoutservice/**'
      - '.github/workflows/**'
    branches:
      - main

jobs:
  docker-workflow:
    uses: ./.github/workflows/_docker-pr.yml
    with:
      project: checkoutservice