name: "PR Currencyservice Service"

on:
  pull_request:
    paths:
      - 'src/currencyservice/**'
      - '.github/workflows/**'
    branches:
      - main

jobs:
  docker-workflow:
    uses: ./.github/workflows/docker-pr.yml
    with:
      project: currencyservice