on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        id: scan
        with:
          dockerfile: ./src/${{ inputs.project }}/Dockerfile
          failure-threshold: error
          output-file: dockerfile.table
      - name: Comment on PR
        uses: actions/github-script@v7
        if: ${{ failure() && steps.scan.conclusion == 'failure' }}
        with:
          script: |
            const { readFileSync } = require('fs')

            const text = readFileSync('./dockerfile.table').trim();

            if (text.length > 0) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "👋 We found the following Dockerfile errors: \n\n\n```\n" + text + "\n```"
              })
            }
  docker-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Split Name
        id: split
        env:
          PATH_CANDIDATE: ${{ inputs.project }}
        run: echo "::set-output name=imagename::${PATH_CANDIDATE##*/}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker
        uses: docker/build-push-action@v4
        with:
          context: ./src/${{ inputs.project }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.split.outputs.imagename }}:${{ github.sha }}
      - name: Scan for Vulnerabilities
        uses: aquasecurity/trivy-action@master
        id: scan
        with:
          image-ref: '${{ steps.split.outputs.imagename }}:${{ github.sha }}'
          exit-code: 1
          output: 'vulnerabilities.table'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
      - name: Comment on PR
        uses: actions/github-script@v7
        if: ${{ failure() && steps.scan.conclusion == 'failure' }}
        with:
          script: |
            const { readFileSync } = require('fs')

            const text = readFileSync('./vulnerabilities.table');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "👋 We found the following vulnerabilities: \n\n\n```\n" + text + "\n```"
            })