name: "Main Frontend"

on:
  push:
    paths:
      - 'src/frontend/**'
    branches:
      - main
jobs:
  docker-workflow:
    uses: ./.github/workflows/_docker-main.yml
    with:
      project: frontend