name: "PR Frontend"

on:
  pull_request:
    paths:
      - 'src/frontend/**'
    branches:
      - main

jobs:
  docker-workflow:
    uses: ./.github/workflows/_docker-pr.yml
    with:
      project: frontend