name: "PR Product Catalog Service"

on:
  pull_request:
    paths:
      - 'src/productcatalogservice/**'
      - '.github/workflows/**'
    branches:
      - main

jobs:
  docker-workflow:
    uses: ./.github/workflows/_docker-pr.yml
    with:
      project: productcatalogservice
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Run Tests
        run: |
          cd ./src/productcatalogservice
          go test