name: "Main Product Catalog Service"

on:
  push:
    paths:
      - 'src/productcatalogservice/**'
      - '.github/workflows/**'
    branches:
      - main
jobs:
  docker-workflow:
    uses: ./.github/workflows/_docker-main.yml
    with:
      project: productcatalogservice