name: "Shared Infra PR"

on:
  pull_request:
    paths:
      - 'src/shared-infra/**'
      - 'infrastructure/**'
    branches:
      - main

jobs:
  docker-workflow:
    uses: ./.github/workflows/_infra-pr.yml
    with:
      project: shared-infra