name: "Shared Infra PR"

on:
  pull_request:
    paths:
      - 'src/shared-infra/**'
      - 'infrastructure/**'
    branches:
      - main

env:
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}

jobs:
  docker-workflow:
    uses: ./.github/workflows/_infra-pr.yml
    with:
      project: shared-infra