name: "Main Shipping Service"

on:
  push:
    paths:
      - 'src/shippingservice/**'
    branches:
      - main
jobs:
  docker-workflow:
    uses: ./.github/workflows/_docker-main.yml
    with:
      project: shippingservice